services:
  - type: web
    name: mahjong-vip-3d
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        sync: false
